"""initial schema

Revision ID: 655768f323e3
Revises: 
Create Date: 2026-09-18 09:22:25.740282

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '655768f323e3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('stream_title', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_verified_or_partner', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'external_id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_kind', sa.String(length=16), nullable=False),
    sa.Column('media_platform', sa.String(length=16), nullable=False),
    sa.Column('media_external_id', sa.String(length=128), nullable=False),
    sa.Column('media_title', sa.String(length=512), nullable=False),
    sa.Column('media_channel_platform', sa.String(length=16), nullable=True),
    sa.Column('media_channel_external_id', sa.String(length=128), nullable=True),
    sa.Column('media_thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('media_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('destination_path', sa.String(length=2048), nullable=False),
    sa.Column('quality_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_downloads_created_at', 'downloads', ['created_at'], unique=False)
    op.create_index('ix_downloads_status', 'downloads', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_platform', sa.String(length=16), nullable=False),
    sa.Column('channel_external_id', sa.String(length=128), nullable=False),
    sa.Column('notify_on_live', sa.Boolean(), nullable=False),
    sa.Column('auto_download', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorites_channel', 'favorites', ['channel_platform', 'channel_external_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('related_media_kind', sa.String(length=16), nullable=True),
    sa.Column('related_media_platform', sa.String(length=16), nullable=True),
    sa.Column('related_media_external_id', sa.String(length=128), nullable=True),
    sa.Column('related_media_title', sa.String(length=512), nullable=True),
    sa.Column('related_media_channel_platform', sa.String(length=16), nullable=True),
    sa.Column('related_media_channel_external_id', sa.String(length=128), nullable=True),
    sa.Column('related_media_thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('related_media_duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_downloads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel_platform', sa.String(length=16), nullable=False),
    sa.Column('channel_external_id', sa.String(length=128), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('quality_preference', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_downloads_channel', 'scheduled_downloads', ['channel_platform', 'channel_external_id'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('playlist_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('media_kind', sa.String(length=16), nullable=False),
    sa.Column('media_platform', sa.String(length=16), nullable=False),
    sa.Column('media_external_id', sa.String(length=128), nullable=False),
    sa.Column('media_title', sa.String(length=512), nullable=False),
    sa.Column('media_channel_platform', sa.String(length=16), nullable=True),
    sa.Column('media_channel_external_id', sa.String(length=128), nullable=True),
    sa.Column('media_thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('media_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playlist_items_playlist_id', 'playlist_items', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlist_items_playlist_id', table_name='playlist_items')
    op.drop_table('playlist_items')
    op.drop_index('ix_scheduled_downloads_channel', table_name='scheduled_downloads')
    op.drop_table('scheduled_downloads')
    op.drop_table('playlists')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_favorites_channel', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_downloads_status', table_name='downloads')
    op.drop_index('ix_downloads_created_at', table_name='downloads')
    op.drop_table('downloads')
    op.drop_table('channels')
    # ### end Alembic commands ###
