"""favorite quality format directory position

Revision ID: b34855f71713
Revises: 655768f323e3
Create Date: 2026-09-19 05:03:32.951060

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b34855f71713'
down_revision: str | Sequence[str] | None = '655768f323e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('preferred_quality', sa.String(length=32), nullable=True))
    op.add_column('favorites', sa.Column('preferred_format', sa.String(length=16), nullable=True))
    op.add_column('favorites', sa.Column('download_directory', sa.String(length=2048), nullable=True))
    # server_default='0' added by hand (autogenerate didn't include one):
    # without it, ALTER TABLE ADD COLUMN ... NOT NULL fails on any
    # database that already has favorites rows — verified by testing
    # this migration against a pre-populated favorites table.
    op.add_column(
        'favorites',
        sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    )
    op.create_index('ix_favorites_position', 'favorites', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorites_position', table_name='favorites')
    op.drop_column('favorites', 'position')
    op.drop_column('favorites', 'download_directory')
    op.drop_column('favorites', 'preferred_format')
    op.drop_column('favorites', 'preferred_quality')
    # ### end Alembic commands ###
